baseURL = "https://www.brucebrotherton.com/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "Bruce Brotherton"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
name = "T-shirts"
url = "https://www.teepublic.com/user/thebruce13"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
URL = "about"
name = "About"
weight = 3
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Bruce Brotherton"
description = "A blog about Web Development, 3D Graphics, Trying to write a novel, and maybe making a video game. Its anything and everyhing I am into."
[params.banner]
heading = "Bruce's Backpack of Ideas"
image = "/images/webpack-render-s.png"
[params.blog]
heading = "Posts from within my backpack. A random collection of thoughts and ideas."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = false
title = "Contact us for more information."
[params.footer]
address = ""
content = "A blog about Web Development, 3D Graphics, Trying to write a novel, and maybe making a video game. Its anything and everyhing I am into. Welcome."
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = ""
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "/images/bathhouse_2.jpg"
[[params.gallery.gallery_item]]
image = "/images/chief_skate_blue_vector2-1.png"
[params.social]
email = "brucebrotherton906@gmail.com"
facebook = ""
instagram = "https://www.instagram.com/coobru/"
linkedin = "https://www.linkedin.com/in/brothertonbruce/"
twitter = "https://twitter.com/brucebrotherton"
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
